# Dependabot pazi, da ne obticimo na zastarelih (in nevzdrzevanih) korakih CI.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "CI"
